# -*- coding: utf-8 -*-
"""NIKHIL_IPL2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mF-VEcwN1zWsr-3RMdCv3_TG2CgFO6pZ
"""

import pandas as pd
import numpy as np

import plotly.express as px

df = pd.read_excel("ipl2022 dataset.xlsx", index_col=0)

df.head()

df.info()

dfg = df.groupby("Team", as_index=False).agg({
    "COST IN â‚¹ (CR.)": "sum",
})

dfg

fig = px.pie(df, values='COST IN â‚¹ (CR.)', names='Team', title='Share of Money Spent By Each Team in IPL 2022')
fig.show()

df["TYPE"].value_counts()

dfg1 = df.groupby(["Team","TYPE"], as_index=False).size()

dfg1

csk = dfg1[dfg1.Team == "Chennai Super Kings"]
dc = dfg1[dfg1.Team == "Delhi Capitals"]
gt = dfg1[dfg1.Team == "Gujarat Titans"]
kkr = dfg1[dfg1.Team == "Kolkata Knight Riders"]
lcg = dfg1[dfg1.Team == "Lucknow Super Giants"]
mi = dfg1[dfg1.Team == "Mumbai Indians"]
pk = dfg1[dfg1.Team == "Punjab Kings"]
rr = dfg1[dfg1.Team == "Rajasthan Royals"]
rcb = dfg1[dfg1.Team == "Royal Challengers Bangalore"]
sh = dfg1[dfg1.Team == "Sunrisers Hyderabad"]

fig = px.pie(csk, values='size', names='TYPE', title='Type of New Players Bought By CSK in IPL 2022')
fig.show()

fig = px.pie(dc, values='size', names='TYPE', title='Type of New Players Bought By DC in IPL 2022')
fig.show()

fig = px.pie(gt, values='size', names='TYPE', title='Type of New Players Bought By GT in IPL 2022')
fig.show()

fig = px.pie(kkr, values='size', names='TYPE', title='Type of New Players Bought By KKR in IPL 2022')
fig.show()

fig = px.pie(lcg, values='size', names='TYPE', title='Type of New Players Bought By LCG in IPL 2022')
fig.show()

fig = px.pie(mi, values='size', names='TYPE', title='Type of New Players Bought By MI in IPL 2022')
fig.show()

fig = px.pie(pk, values='size', names='TYPE', title='Type of New Players Bought By PK in IPL 2022')
fig.show()

fig = px.pie(rr, values='size', names='TYPE', title='Type of New Players Bought By RR in IPL 2022')
fig.show()

fig = px.pie(rcb, values='size', names='TYPE', title='Type of New Players Bought By RCB in IPL 2022')
fig.show()

fig = px.pie(sh, values='size', names='TYPE', title='Type of New Players Bought By SH in IPL 2022')
fig.show()

